### ISSUE TITLE
Modify expected input given that Spotify no longer uses URIs for playlists.

### ISSUE THREAD

**Issue by topotech** [plamere/OrganizeYourMusic#14]
Spotify no longer offers an option to copy URIs, at least on playlist. It isn't hard to manually construct a playlist URI from user's profile URL and the playlist URL:

`spotify:user:{USER_ID}:playlist:{PLAYLIST_ID}`

but maybe it would be a good idea to use proper https URLs instead of Spotify URIs.

**Comment by sensodejay** [comment]
The Spotify URI can be still be accessed see in the spotify client see the following procedure https://community.spotify.com/t5/FAQs/What-s-a-Spotify-URI/ta-p/919201

**Comment by topotech** [comment]
Excellent, I didn't know that holding a modifier key like Ctrl or Alt the menu changed. Thanks! Issue closed.
